store:
  availabilities:
    - German
    - International
  default_locale: de_DE
  localizations:
    - de_DE
    - en_GB
  categories:
    - Sonderfunktionen
  type: extension
  icon: src/Resources/config/plugin.png
  automatic_bugfix_version_compatibility: true
  description:
    de: file:docs/store.md
    en: file:docs/store.en.md
  installation_manual:
    de: file:docs/manual.md
    en: file:docs/manual.en.md
  tags:
    de:
      - Hersteller
      - SEO
      - Storefront
    en:
      - Manufacturer
      - SEO
      - Storefront
  videos:
    de: []
    en: []
  highlights:
    de:
      - Herstellersuche
      - Zusätzliche CMS Elemente
      - CMS Seite für Hersteller mit Produktübersicht
      - Zusätzliche Daten - Adresse, Geokoordinaten, Kontaktmöglichkeiten
      - Anspruchsvolle Gestaltungsmöglichkeiten
    en:
      - Manufacturer search
      - Additional CMS elements
      - MS page for manufacturers with product overview
      - Additional data—address, coordinates, contact details
      - Advanced design options
  features:
    de: []
    en: []
  faq:
    de: []
    en: []
  images:
    - file: docs/images/admin-1.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-2.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-3.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-4.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-5.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-7.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
    - file: docs/images/admin-8.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
    - file: docs/images/storefront-manufacturer-detail.png
      activate:
        de: true
        en: true
      preview:
        de: true
        en: true
      priority: 0
    - file: docs/images/storefront-manufacturer-listing.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 100
    - file: docs/images/storefront-product-detail.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/storefront-search.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0

changelog:
  enabled: true
  pattern: '^[A-Z].{19,}'
  template: |
    {{range .Commits}}- {{ .Message }}
    {{end}}

build:
  zip:
    pack:
      excludes:
        paths:
          - docs
          - TODO.md
